name: Check for updates
run-name: "Automated update of ${{ github.ref_name }} by @${{ github.actor }}"

on:
  schedule:
    - cron: '59 23 * * *'
  workflow_dispatch:

jobs:
  update-all:
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/unstable' }}
    env:
      GH_TOKEN: ${{ github.token }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.PULL_PUSH }}

      - name: Check for updates
        id: check-updates
        run: |
          chmod +x scripts/check_updates.sh
          ./scripts/check_updates.sh

          if [[ -n "$(git status --porcelain)" ]]; then
            echo "has_updates=true" >> "$GITHUB_OUTPUT"
          else
            echo "No updates found"
            echo "has_updates=false" >> "$GITHUB_OUTPUT"
          fi

      - name: Create update branch and commit
        if: steps.update.outputs.has_updates == 'true'
        run: |
          BRANCH="automated-update-$(date +%Y%m%d-%H%M%S)"

          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git checkout -b "$BRANCH"

          git add srcpkgs
          git commit -m "Automated Sonic-DE package updates"

          echo "BRANCH=$BRANCH" >> "$GITHUB_ENV"

      - name: Push update branch
        if: steps.update.outputs.has_updates == 'true'
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.PULL_PUSH }}
          branch: ${{ env.BRANCH }}

      - name: Create Pull Request
        if: steps.update.outputs.has_updates == 'true'
        env:
          GH_TOKEN: ${{ secrets.PULL_PUSH }}
        run: |
          gh pr create \
            --base unstable \
            --head "${{ env.BRANCH }}" \
            --title "Automated Sonic-DE package updates" \
            --body "This PR was automatically generated by the package updater workflow."
